version: '3.4'

services:
  music_cleaner:
    restart: always
    build:  ./tbot

    stdin_open: true
    tty: true
    volumes:
      - ./tbot/src:/home/node/src

    environment:
      - TG_BOT_API_TOKEN




networks:
  default:
    driver: bridge
