version: '3.4'

services:
  music_cleaner:
    restart: always
    build: .
    stdin_open: true
    tty: true
    volumes:
      - ./src:/home/node/src

    environment:
      - RMQ_USERNAME
      - RMQ_PASSWORD

      - TG_BOT_API_TOKEN

    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=$RMQ_USERNAME
      - RABBITMQ_DEFAULT_PASS=$RMQ_PASSWORD

    ports:
      - "5672:5672"
      - "15672:15672"

    volumes:
      - ./rmq-data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  python-toolset:
    build: python
    restart: always
    stdin_open: true
    tty: true

    environment:
      - RMQ_USERNAME
      - RMQ_PASSWORD

      - TG_API_ID
      - TG_API_HASH

    volumes:
      - ./python:/app

    depends_on:
      rabbitmq:
        condition: service_healthy

  web:
    build: ./web
    entrypoint: bundle exec rails s -b 0.0.0.0 -p 8080
    volumes:
      - ./web:/app

    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST=postgres

    ports:
      - "8080:8080"

  postgres:
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD

    image: postgres

    volumes:
      - ./psql-data:/var/lib/postgresql/data

    ports:
      - 5432:5432

    restart: always

    stdin_open: true
    tty: true

networks:
  default:
    driver: bridge
