version: "3.3"

services:
  neo4j:
    container_name: neo4j

    image: neo4j
    ports:
    - 7474:7474
    - 7687:7687
    volumes:
      - $HOME/neo4j/data:/data
    restart: always
      #network_mode: "host"

