version: '3.4'

services:


  rabbitmq:
    image: rabbitmq:3-management
    restart: always

    networks:
      - shared_network

    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=$RMQ_USERNAME
      - RABBITMQ_DEFAULT_PASS=$RMQ_PASSWORD

    ports:
      - "5672:5672"
      - "15672:15672"

    volumes:
      - ~/rmq-data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5


networks:
  shared_network:
    external: true
