version: '3.4'

services:
  music_cleaner:
    restart: always
    build: .
    stdin_open: true
    tty: true
    volumes:
      - ./src:/home/node/src

    environment:
      - RMQ_USERNAME
      - RMQ_PASSWORD
      - RMQ_HOST

      - TG_BOT_API_TOKEN

    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=$RMQ_USERNAME
      - RABBITMQ_DEFAULT_PASS=$RMQ_PASSWORD

    ports:
      - "5672:5672"
      - "15672:15672"

    volumes:
      - ./rmq-data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  python-toolset:
    build: python
    restart: always
    stdin_open: true
    tty: true

    environment:
      - RMQ_USERNAME
      - RMQ_PASSWORD
      - RMQ_HOST

      - TG_API_ID
      - TG_API_HASH

    volumes:
      - ./python:/app

    depends_on:
      rabbitmq:
        condition: service_healthy

  neo4j:
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - $HOME/neo4j/data:/data
    restart: always

networks:
  default:
    driver: bridge
