FROM node:16-alpine

USER node

WORKDIR /home/node

COPY --chown=node:node ./package.json .

# RUN npm --silent i

USER root

# RUN npm install -g nodemon

USER root


CMD yarn && yarn run nodemon node src/main.js
