# syntax = docker/dockerfile:experimental

FROM python:3.9

WORKDIR /app


RUN apt-get update && \
    apt-get install -y curl && \
    curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - && \
    apt-get install -y nodejs

RUN apt-get install -y yarn


RUN --mount=type=cache,target=/root/.npm npm install -g nodemon

COPY requirements.txt .

RUN --mount=type=cache,target=/root/.cache/pip  pip install -r ./requirements.txt

RUN sh python/setup.sh

CMD nodemon --exec .venv/bin/python3 src/main.py
